### ISSUE TITLE
Dashboard does not install properly, 'module' object has no attribute 'IResourceView'

### ISSUE THREAD

**Issue by sepandar-sepehr** [ckan/ckanext-dashboard#15]
I just installed dashboard, but I get this error:

  File "/home/thinkdata/ckan/lib/default/src/dashboard/ckanext/dashboard/plugin.py", line 20, in DashboardView
    p.implements(p.IResourceView, inherit=True)
AttributeError: 'module' object has no attribute 'IResourceView'

**Comment by vitorbaptista** [comment]
Hi @sepsep,

Thanks for pointing me this problem.

You're probably using an old version of CKAN. This (and all other resource views, as ckanext-basiccharts and ckanext-mapviews) depend on CKAN's master branch, that still wasn't released (it'll be CKAN 2.3). Please try again using master. If you still have problems, don't hesitate to reopen this issue.

Cheers!

**Comment by sepandar-sepehr** [comment]
Yes I am using the 2.2 version. I renamed IResourceView to IResourcePreview and passed that error, but then I get some other errors that I posted somewhere else. I had too many issues with master branch that's why I went back to 2.2.

**Comment by vitorbaptista** [comment]
This extension depends on the resource views feature that's currently only available on CKAN master, which as you noticed can be a bit unstable. Unfortunately, your two options to be able to use this are either to use CKAN master or wait for the 2.3 release.

**Comment by sepandar-sepehr** [comment]
OK thanks for the reply. I'll wait for 2.3 since I have to use it for deployment.
