### ISSUE TITLE
API CKAN ERROR USING CKNEXT-DASHBOARD

### ISSUE THREAD

**Issue by Pilarbr82** [ckan/ckanext-dashboard#18]
Hi!

We have an issue with the plugin. We were posting documents through the API using NIFI. Everythings was going well. When we started to use the "ckanext-dashboard" plugin, we start to get internal servers error. (we checked it with the postman). we have just disable the plugin and everything works again.

Does anybody knows hoy to solve this?

Thank u very much

**Comment by davidshumway** [comment]
Hi, Did you find the solution to this issue?
